### Cargar dataframe de Canada

In [1]:
# Library for data analysis and manipulation
import pandas as pd
# Library for math operations with matrices and vectors
import numpy as np

In [2]:
df = pd.read_excel('canada.xlsx')

In [3]:
df

,Tipo,Pais,Area,Continente,Region,Nombre de region,Tipo de region,1980,1981,1982,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Immigrants,Afghanistan,935,Asia,5501,Southern Asia,Developing regions,16,39,39,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Immigrants,Albania,908,Europe,925,Southern Europe,Developed regions,1,0,0,...,1450,1223,856,702,560,716,561,539,620,603
2,Immigrants,Algeria,903,Africa,912,Northern Africa,Developing regions,80,67,71,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,Immigrants,American Samoa,909,Oceania,957,Polynesia,Developing regions,0,1,0,...,0,0,1,0,0,0,0,0,0,0
4,Immigrants,Andorra,908,Europe,925,Southern Europe,Developed regions,0,0,0,...,0,0,1,1,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Immigrants,Viet Nam,935,Asia,920,South-Eastern Asia,Developing regions,1191,1829,2162,...,1816,1852,3153,2574,1784,2171,1942,1723,1731,2112
191,Immigrants,Western Sahara,903,Africa,912,Northern Africa,Developing regions,0,0,0,...,0,0,1,0,0,0,0,0,0,0
192,Immigrants,Yemen,935,Asia,922,Western Asia,Developing regions,1,2,1,...,124,161,140,122,133,128,211,160,174,217
193,Immigrants,Zambia,903,Africa,910,Eastern Africa,Developing regions,11,17,11,...,56,91,77,71,64,60,102,69,46,59
194,Immigrants,Zimbabwe,903,Africa,910,Eastern Africa,Developing regions,72,114,102,...,1450,615,454,663,611,508,494,434,437,407

### 1. Agregar las siguientes columnas al dataframe: migración 80s, migración 90s, migracion 2000s, migración 2010s y total migración

In [5]:
df["migracion 80s"] = df.loc[:, list(range(1980,1989))].sum(axis=1)
df["migracion 90s"] = df.loc[:, list(range(1990,1999))].sum(axis=1)
df["migracion 2000s"] = df.loc[:, list(range(2000,2009))].sum(axis=1)
df["migracion 2010s"] = df.loc[:, list(range(2010,2014))].sum(axis=1)
df["migracion 2010s"] = df.loc[:, list(range(1980,2014))].sum(axis=1)

In [6]:
df

,Tipo,Pais,Area,Continente,Region,Nombre de region,Tipo de region,1980,1981,1982,...,2008,2009,2010,2011,2012,2013,migracion 80s,migracion 90s,migracion 2000s,migracion 2010s
0,Immigrants,Afghanistan,935,Asia,5501,Southern Asia,Developing regions,16,39,39,...,2111,1746,1758,2203,2635,2004,2617,13450,28755,6596
1,Immigrants,Albania,908,Europe,925,Southern Europe,Developed regions,1,0,0,...,560,716,561,539,620,603,6,1304,10083,1720
2,Immigrants,Algeria,903,Africa,912,Northern Africa,Developing regions,80,67,71,...,4005,5393,4752,4325,3774,4331,837,10764,32440,12851
3,Immigrants,American Samoa,909,Oceania,957,Polynesia,Developing regions,0,1,0,...,0,0,0,0,0,0,2,2,1,0
4,Immigrants,Andorra,908,Europe,925,Southern Europe,Developed regions,0,0,0,...,0,0,0,0,1,1,2,6,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Immigrants,Viet Nam,935,Asia,920,South-Eastern Asia,Developing regions,1191,1829,2162,...,1784,2171,1942,1723,1731,2112,27634,36307,19103,5396
191,Immigrants,Western Sahara,903,Africa,912,Northern Africa,Developing regions,0,0,0,...,0,0,0,0,0,0,0,1,1,0
192,Immigrants,Yemen,935,Asia,922,Western Asia,Developing regions,1,2,1,...,133,128,211,160,174,217,54,622,1267,545
193,Immigrants,Zambia,903,Africa,910,Eastern Africa,Developing regions,11,17,11,...,64,60,102,69,46,59,153,497,572,217
194,Immigrants,Zimbabwe,903,Africa,910,Eastern Africa,Developing regions,72,114,102,...,611,508,494,434,437,407,603,618,4861,1365

### 2. Crear un nuevo df con la migración total por cada continente (solo 5 continentes) y convertirlo a Schema

In [7]:
df.Continente.unique()

array(['Asia', 'Europe', 'Africa', 'Oceania',
       'Latin America and the Caribbean', 'Northern America'],
      dtype=object)

In [ ]:

columnas = ["Asia", "Europe","Africa","Oceania","America"]
nuevo_data = pd.DataFrame(columns = columnas)

In [ ]:
for i in indice:
    Entire, Private, Shared = df[df["municipio"]==i]["room_type"].value_counts() 
    nuevo_data.xs(i)["# hab. individual"] = Private
    nuevo_data.xs(i)["#cas/dep"] = Entire
    nuevo_data.xs(i)["compartido"] = Shared
nuevo_data

### 3. Crear un schema con los paises de oceania y las columnas de migración 80s, migración 90s, migracion 2000s, migración 2010s y total migración

### 4. Mostrar las estadisticas del Schema

### 5. Mostar las columnas del Schema en una lista

### 6. Encontrar el promedio, la desviación estandard, el skewnesss y kurtosis de las columnas: migración 80s, migración 90s, migracion 2000s, migración 2010s y total migración

### 7. Obtener los valores maximos de las columnas

### 8. Cambiar el nombre de los paises a mayusculas utilizando .replace()

### 9. Encontrar el pais con más migración en los 90s